### ISSUE TITLE
Add an option to test with master or release packages ?

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#100]
It would be good if developers can have an option to choose to test with master or released versions of all packages. That way we can be confident that our next release won't cause any problems.

**Comment by nitisht** [comment]
we currently use the latest released version of each tool/sdk in mint. I think that is serving well, and no specific cases were found where we needed to test a specific version of a SDK. 

@vadmeste if you agree, shall we close this issue?

**Comment by vadmeste** [comment]
Yeah, the thing, is that.. we don't release SDKs that often, and it is good to see new tests added in SDKs can detect any new regression found in Minio server - before it is too late -

I'll bring this up in the next meeting.

**Comment by nitisht** [comment]
Understood..will keep this open till we decide on how to go ahead

**Comment by deekoder** [comment]
What do we want to do about this. If we are not fixing we can close and reopen later.

**Comment by harshavardhana** [comment]
> Yeah, the thing, is that.. we don't release SDKs that often, and it is good to see new tests added in SDKs can detect any new regression found in Minio server - before it is too late -

Actually this is not true @vadmeste we do release SDKs quickly when we have new changes in place, in-fact with `q` automation it is quite simple now. I don't think this issue is worth the effort anymore.

**Comment by hayashiki** [comment]
ETA: 2018-03-08 12:00

**Comment by kannappanr** [comment]
closing this issue as won't fix.
