### ISSUE TITLE
If SERVER_ENDPOINT is not passed, download Minio server and runs it automatically

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#101]
If the environment variable SERVER_ENDPOINT is not specified, it would be great if Mint can download the Minio server and runs it using a random port, then runs all sdk tests.

**Comment by NitishT** [comment]
@vadmeste there is another pod to automate Mint testing, https://github.com/minio/mint/projects/2

That will cover the aspect of downloading and deploying Minio server and then running Mint against it.

**Comment by vadmeste** [comment]
oups, got it.
