### ISSUE TITLE
Refactor: Replace log/print statements with standard Ruby logger class.

### ISSUE THREAD

**Issue by ebozduman** [minio/mint#102]
This is to replace existing log/print methods with standard Ruby logger library methods.
Existing print/logging methods are:
`print_title(title)`
`print_log(log_msg, arg='')`
`print_logn(log_msg, arg='')`
`print_status(result, e='')`

**Comment by nitisht** [comment]
Ruby SDK logs error in standard mint log format. So this is not required for now
