### ISSUE TITLE
Update mc to output new mint log format

### ISSUE THREAD

**Issue by NitishT** [minio/mint#114]
`mc` logs need to be updated in the format below so that `mint` logs can be easily parsed.

```
{
    "name":"mc", // SDK Name
    "function":"testPresignGetObject", // Test function name
    "description": "test function description (optional)", //  Test function description
    "args":"", // key value map, varName:value. Only arguements that devs may be interested in
    "duration":"", // duration of the whole test
    "status":"", // can be PASS, FAIL, NA
    "alert":"failed to download pre-signed object(optional)", // error related, human readable message. Should be taken care of if present
    "error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
}
```

**Comment by ebozduman** [comment]
Question: Do we  need to make distinction for required/mandatory and optional arguments when we list the arguments? aws-sdk-ruby has that information and if decided it can be included in the `"args":` field.

By the way, aws-sdk-ruby provides an array of strings for `"args":` field, like:
```
{
  "name": "aws-sdk-ruby",
  "function": "listBucketsTest",
  "args": [
    "bucket_name_list"
  ],
  "comment": "Tests listBuckets api command by creating new buckets from bucket_name_list",
  "status": "PASS"
}
```

**Comment by ebozduman** [comment]
I think we also need to discuss how to differentiate between the same test running with different arg values to test different scenarios. At this point, `"comment":` being set inside the test, there is no way to differentiate the 2 tests. We can make the test information/comment as an additional argument for the test, but I don't think that is a good idea. Any thoughts?

**Comment by NitishT** [comment]
@ebozduman I think the `args` field doesn't really solve a purpose. Instead we can have `comment` moved just below the `function` section and have `comment` indicate short description of what the test is supposed to validate.

**Comment by kannappanr** [comment]
@NitishT ,

 There was a change in the log format. You are missing "message" field. AB asked us to remove the description field and add the parameters in the function field. Here is a modified version of a sample log entry

{
    "name":"mc", // SDK Name
    "function":"testPresignGetObject(int index)", // Test function name
    "args":"", // key value map, varName:value. Only arguements that devs may be interested in
    "duration":"1.5 s", // duration of the whole test in seconds
    "status":"", // can be PASS, FAIL, NA
    "alert":"Information like whether this is a Blocker/ Gateway, Server etc can go here", 
    "message":" descriptive error message" // error related, human readable message. Should be taken care of if present
    "error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
}

**Comment by ebozduman** [comment]
I think there are couple of things I'd like to suggest/clarify and confirm with the team and AB:

1. `"function"`: My understanding is that this field was going to be the test method name, like "", not the api name.
2. `"description"`: I'd like to suggest keeping this optional field for those test cases which may need extra words to explain what is happening inside the test method when the name of the test method is not self-explanatory

**Comment by balamurugana** [comment]
>     "function": My understanding is that this field was going to be the test method name and its arguments, like bucketExistsNegativeTest(bucket_name), not the api name bucketExists(bucket_name).

For SDK, my recommendation is to use test method name than API name.
For tools, full command line like `mc cp file minio/mybucket/myobject`

>     "description": I'd like to suggest keeping this optional field for those test cases which may need some extra words to explain what is happening inside the test method when the name of the test is not self-explanatory.

As we send only fields with values, I am OK with this

**Comment by NitishT** [comment]
@kannappanr @ebozduman @balamurugana can we have the final/consolidated log format pasted here, so it doesn't lead to rework.

**Comment by kannappanr** [comment]
Latest Log Format.
{
"name":"mc", // SDK Name
"function":"makeBucket(String bucketName)", // API name
"args":"", // key value map, varName:value. Only arguements that devs may be interested in
"duration":"15 ", // duration of the whole test in milli seconds
"status":"", // can be PASS, FAIL, NA
"alert":"Information like whether this is a Blocker/ Gateway, Server etc can go here",
"message":" descriptive error message" // error related, human readable message. Should be taken care of if present
"error":"stack-trace/exception message(only in case of failure)" // actual low level exception/error thrown by the program
}

**Comment by ebozduman** [comment]
The above information Kannappan put together came from an informal meeting Kannappan, AB and I had.
We can definitely have another meeting to talk about the logic and reasons why the latest format is decided.

**Comment by NitishT** [comment]
> The above information Kannappan put together came from an informal meeting Kannappan, AB and I had. We can definitely have another meeting to talk about the logic and reasons why the latest format is decided.

Thanks @ebozduman . We can do that, but as long as this format is agreed upon and approved by @abperiasamy lets adhere to this. We'll review current PRs and implement new logging based on this format.
