### ISSUE TITLE
[test] Add tests to verify if object name with "/" doesn't peg the CPU load

### ISSUE THREAD

**Issue by harshavardhana** [minio/mint#146]
https://github.com/minio/minio/pull/4962 related to the fix done on server side.

**Comment by deekoder** [comment]
Please clarify is it done and  can beclosed?

**Comment by harshavardhana** [comment]
> Please clarify is it done and can beclosed?

Its not done yet @deekoder . We need to add a test.

**Comment by harshavardhana** [comment]
Thought about this but there is just no real way to validate this.. through mint.

**Comment by balamurugana** [comment]
Can this be possible with aws sdks and/or s3cmd awscli tools?

**Comment by harshavardhana** [comment]
It is not possible through command line tools AFAIK. But it is not possible to know if server is using 100% CPU from mint. So we need to perhaps bring a unit test on server instead.

**Comment by balamurugana** [comment]
I guess no test will help to find CPU usage ie can't check CPU usage in the test  I think the goal is to test whether server returns a failure or not.

**Comment by nitisht** [comment]
@harshavardhana if there is no way to add this, shall we close this?

**Comment by harshavardhana** [comment]
Closing since it's not possible to reproduce this to a measurable value.
