### ISSUE TITLE
mint logs need to be more descriptive.

### ISSUE THREAD

**Issue by poornas** [minio/mint#151]
1. Logging just the function signature is not very useful when analyzing mint failures - an additional description of test / naming test descriptively will help (e.g. "PutObject test with custom metadata") 
2. Currently many SDK's log the errors as PASS/FAIL with no meaning error message associated with it. 
3. SDK's stop on the very first failure and do not proceed further. A better approach would be to run all tests and raise issues for failures against the respective SDK/Mint so that they can be tracked and resolved for faster iterations. Playing catch up will be really slow when Mint and SDK updates occur at tandem.

**Comment by nitisht** [comment]
This needs a larger discussion, specially with @abperiasamy , can be blocked till we discuss with him.

**Comment by nitisht** [comment]
@poornas with the recent discussion, do you think we can close this issue?
