### ISSUE TITLE
Add tests for gateway in mint

### ISSUE THREAD

**Issue by deekoder** [minio/mint#16]

**Comment by hackintoshrao** [comment]
As discussed  in https://github.com/minio/minio/pull/4384 , need to design tests which are specific for gateways with different backends, ex: `mint --gateway azure ENDPOINT`.

**Comment by hackintoshrao** [comment]
List of GCS related tests to be added, maintaining it here temporarily, 

- https://github.com/minio/minio/issues/4397
- https://github.com/minio/minio/issues/4400
- https://github.com/minio/minio/issues/4401
- https://github.com/minio/minio/issues/4395
- https://github.com/minio/minio/issues/4380

**Comment by rushenn** [comment]
ETA:2017-06-26 12:00

**Comment by kannappanr** [comment]
Mint will be testing S3 APIs primarily. Need to go through the issues mentioned and open relevant issues in mint.

**Comment by nitisht** [comment]
closing this for now as we don't have enough cycles to do this
