### ISSUE TITLE
Awscli and mc should handle tests where the behavior is different between Minio and S3

### ISSUE THREAD

**Issue by kannappanr** [minio/mint#166]
Mint has a negative functional test for Awscli and mc where the object name is /2123123\\123\n. It will fail in Minio as the test expects it to. This is a valid object as far as AWS is concerned, so the object gets created and the test fails. We need to either skip the test in the case of AWS, or not include this test at all.

**Comment by nitisht** [comment]
With removal of the relevant test cases from mc/awscli, I think this issue is not applicable @kannappanr . If you agree we can close this issue

**Comment by kannappanr** [comment]
Yes, this issue can be closed
