### ISSUE TITLE
Generated log entry is not parsable using jq

### ISSUE THREAD

**Issue by kannappanr** [minio/mint#167]
Here is the entry that fails to parse via jq

{"name": "awscli", "duration": 4655, "function": "aws --endpoint-url http://192.168.1.200:9000 s3api put-object --body /mint/data/datafile-1-MB --bucket awscli-mint-test-bucket-21197 --key /2123123\\123\n", "status": "FAIL", "error": "{    "ETag": "\"60e7dc00791f53078f1894fc6a758a66\""}"}

We need to figure out why it fails to parse and fix it.

**Comment by harshavardhana** [comment]
> {"name": "awscli", "duration": 4655, "function": "aws --endpoint-url http://192.168.1.200:9000 s3api put-object --body /mint/data/datafile-1-MB --bucket awscli-mint-test-bucket-21197 --key /2123123\123\n", "status": "FAIL", "error": "{ "ETag": ""60e7dc00791f53078f1894fc6a758a66""}"}

ETag needs to not have double brackets not sure why they have it.

**Comment by balamurugana** [comment]
The error message `"error": "{ "ETag": ""60e7dc00791f53078f1894fc6a758a66""}"` is not useful.  We can not conclude anything with this.

**Comment by nitisht** [comment]
Minio server doesn't allow object names like `/2123123\\123`, while S3 allows it, so object creation with key `/2123123\\123` passes with s3 gateway -- causing the test itself to fail. 

Not sure if minio should actually block object creation requests like this or just pass through.

**Comment by harshavardhana** [comment]
> Not sure if minio should actually block object upload requests like this or just pass through.

There is only one condition this test should fail

 - Server returned an error which is unexpected for the test. 

In all other cases its a success.
