### ISSUE TITLE
Check server's list parts response returning correct ETags

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#18]
https://github.com/minio/minio/issues/4294: the gateway was returning ETags with double double quotes. It would be great if mint can detect this problem.

**Comment by hackintoshrao** [comment]
Yes, We can to add this to generic tests I believe, this applies to Minio server response as well right ?

**Comment by vadmeste** [comment]
> this applies to Minio server response as well right ?

Yes

**Comment by kannappanr** [comment]
@nitisht Can you please update if we have implemented this in any of the functional tests in the SDKs

**Comment by nitisht** [comment]
closing this for now as we don't have enough cycles to do this now
