### ISSUE TITLE
Question about consistency checks v/s eventual consistency checks added in tests

### ISSUE THREAD

**Issue by harshavardhana** [minio/mint#183]
This discussion starts from the question here https://github.com/minio/mint/pull/177, why do we need to add delays specifically for different gateways.  This happens with Backblaze B2 for bucket policies in minio-java as well.  

The reason we need to discuss this is to see if its a good idea to add these delays in our test code, perhaps even come up with modes for gateway where we have a separate setup and teardown such that we do not have to relax actual minio server tests which are strongly consistent and do not have to make them eventual consistent.

// cc @krisis @balamurugana @nitisht @kannappanr @ebozduman

**Comment by krisis** [comment]
@ebozduman @harshavardhana this issue should be marked blocked until we have a discussion.

**Comment by kannappanr** [comment]
@krisis to discuss with @harshavardhana and unblock this issue

**Comment by deekoder** [comment]
Decided to simply add the delay to acceptable levels and so its not an issue anymore.
