### ISSUE TITLE
Test to fetch index.html

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/mint#212]
Need a functional test to fetch index.html and other web-UI assets (logo, bundle.js etc)

**Comment by krishnasrinivas** [comment]
@shruthied this test is to ensure that minio server is serving all the files for browser access:

```
curl -H "User-Agent: Mozilla" localhost:9000/minio/chrome.png > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/favicon.ico > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/firefox.png > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/index.html > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/loader.css > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/logo.svg > /dev/null
curl -H "User-Agent: Mozilla" localhost:9000/minio/safari.png > /dev/null
```

The above commands can be run in a bash script, for each curl request you can ensure that curl exits with 0 exit status.
You can create a new directory `run/core/browser-assets` for these tests.

**Comment by kannappanr** [comment]
@krishnasrinivas This returns 0 even if Browser is turned off in config.json. Returns 7 if the server is not running. Should we check the contents also?

**Comment by deekoder** [comment]
@nitisht  yes its an issue but since we have not fixed it, i think we can close and reopen later when we can work on them. Let me know what you think.

**Comment by nitisht** [comment]
agreed @deekoder . Closing this
