### ISSUE TITLE
Accept SSL cert as an argument in awscli functional tests

### ISSUE THREAD

**Issue by ebozduman** [minio/mint#221]
awscli test ran against the latest minio release, `minio.RELEASE.2017-11-15T22-20-02Z`, fails with the following error message:
```
{
  "name": "awscli",
  "duration": 11767,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)"
}
```
We need to support self-signed certificates.

**Comment by deekoder** [comment]
Not clear on whether we need this still. Let's discuss about this.

**Comment by deekoder** [comment]
I believe we dont need this anymore. Closing as won't fix. Please re-open if i am mistaken about this.
