### ISSUE TITLE
[Automation] Identify how to run mint for minio pull request

### ISSUE THREAD

**Issue by balamurugana** [minio/mint#243]
Mint needs to be run for a pull request of https://github.com/minio/minio/.  Identify below
1. Setup kubernetes to run minio pods in below modes with/without region configured.
    * Single node FS
    * Multi node FS (NAS backend) 
    * Single node Erasure
    * Multi-node Erasure
    * Single node gateway:azure
    * Single node gateway:b2
    * Single node gateway:gcs
    * Single node gateway:manta
    * Single node gateway:oss
    * Single node gateway:s3
    * Single node gateway:sia
2. Setup/pull/build minio pull request
3. Run docker container in step 2 in various mode listed in step 1 by identifying receipes in kubernetes
4. Run mint against minio setup running in various modes mentioned in step 1
5. Collect mint logs for various mint runs happened in step 4
6. Put identified solutions in a small working script(s).

**Comment by harshavardhana** [comment]
> Single node gateway:azure
> Single node gateway:b2
> Single node gateway:gcs
> Single node gateway:manta
> Single node gateway:oss
> Single node gateway:s3
> Single node gateway:sia

@balamurugana i think we are not testing sia, manta until they have fully implemented S3 support.  Also for others like OSS, B2 requires us to buy subscription to test on a continuous basis. 

To start i think gcs, azure, s3 is good to complete.

**Comment by balamurugana** [comment]
Refer findings at https://gist.github.com/balamurugana/c59e868a36bb8a549fe863d22d6f0678

**Comment by deekoder** [comment]
Since this is completed, this should have been closed as fixed. Doing that now.
