### ISSUE TITLE
[Automation] Identify how github notifies new PR/PR lifecycle to external service

### ISSUE THREAD

**Issue by balamurugana** [minio/mint#244]
1. Need to identify how github notifies mint automation service for new PR submission and PR lifecycle (closed, merged etc) for https://github.com/minio/minio/.  Below things need to be found
2. Need to identify how mint automation add/edit comments in minio PR.
3. Put identified solutions in a small working script(s).

**Comment by balamurugana** [comment]
Refer https://gist.github.com/balamurugana/d95c824963332e049fd2808717aba1b7

**Comment by deekoder** [comment]
@balamurugana  this should be closed i am guessing. Marking fixed and closing.
