### ISSUE TITLE
Check metadata after an object copy operation

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#265]
Refer to this https://github.com/minio/minio/issues/5622 for more understanding of the problem.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/pull/944 adds the test

**Comment by kannappanr** [comment]
We can reference this issue in that PR and close this once that is merged

**Comment by kannappanr** [comment]
minio/minio-go#944 is merged, so closing this issue
