### ISSUE TITLE
Avoid running encryption tests when HTTPS is not enabled

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#266]
mint will fail when Minio server doesn't have a TLS certificate, currently minio-go says it needs a https connection to test encryption and fails.

It would be useful to have this feature, otherwise a user (me!) will be struggling in inserting a TLS certificate in Docker container

**Comment by harshavardhana** [comment]
minio-go tests never run when ENABLE_HTTPS=0 is enabled are you not setting that? @vadmeste

**Comment by harshavardhana** [comment]
Its mentioned here https://github.com/minio/mint#mint-environment-variables

**Comment by vadmeste** [comment]
yeah.. I was testing using mint:latest and not mint:edge. Checked with mint:edge, closing this.
