### ISSUE TITLE
Option to not exit on failure?

### ISSUE THREAD

**Issue by dpsi** [minio/mint#286]
Hi,
Is there an option to try to run all tests and ignore failures? For example if a go tests fails, it doesn't run any of the other tests. The only workaround I have found is to remove the go tests completely, only for another sdk to also fail and exit.

**Comment by harshavardhana** [comment]
> Hi,
> Is there an option to try to run all tests and ignore failures? For example if a go tests fails, it doesn't run any of the other tests. The only workaround I have found is to remove the go tests completely, only for another sdk to also fail and exit.

this is intentional @dpsi you can pick and run the tests you want as well 

```
docker run ... minio/mint aws-sdk-java
```

**Comment by dpsi** [comment]
So I would have to omit entire classes of tests then? It seems flawed to me that a single failure in one suite of tests just exits out of the container completely. 

Looking at the code, it looks like a pain to change this behaviour since all the tests cases are hard coded to exit on exception.

**Comment by harshavardhana** [comment]
> So I would have to omit entire classes of tests then? It seems flawed to me that a single failure in one suite of tests just exits out of the container completely.
> 
> Looking at the code, it looks like a pain to change this behaviour since all the tests cases are hard coded to exit on exception.

you can type many other tests to `docker run ... minio/mint aws-sdk-java mc s3cmd` so you are skipping something that fails, the point here is to fix your server. 

We will not proceed on a failure then it will cause more problems and possibly even ignore the issue.

**Comment by dpsi** [comment]
Thanks, I guess this project isn't what I am looking for.

I was looking for minio/s3verify or ceph/s3-tests type of tool.
