### ISSUE TITLE
Building docker container fails because of version mismatch

### ISSUE THREAD

**Issue by amyjzhu** [minio/mint#301]
Not sure if I'm doing something wrong here, but it looks like building the mint docker container fails at build/mc/install.sh because the mc version at https://api.github.com/repos/minio/mc/releases/latest (updated October 18) doesn't match the artifacts downloadable at https://dl.minio.io/client/mc/release/linux-amd64/ (October 31). If I am misled, any advice...? 

Thanks

**Comment by harshavardhana** [comment]
Fixed @amyjzhu - closing.
