### ISSUE TITLE
Test suite fails when running behind traefik using let's encrypt certificate

### ISSUE THREAD

**Issue by zaibon** [minio/mint#313]
I've been working on a project where I implement the gateway interface of minio to reach my backend.
To make sure I implemented everything properly I tried to run the mint test suite on my minio implementation.

I discovered some strange behaviors:
- when running mint directly on my minio, everything works fine.
- When running traefik as a proxy to my minio, test suite works if I run it over http with `ENABLE_HTTPS=0`
- When running traefik as a proxy to my minio with automatic HTTPS using let's encrypt, the mint test suite fails immediately.

Here is the logs of mint when running against traefik with auto https:
```
To get logs, run 'docker cp 147658e966c9:/mint/log /tmp/mint-logs'
(1/13) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-4oea0ftoysx5qy",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 347,
  "error": "AWS S3 error code mismatch",
  "function": "PresignedPut",
  "message": "AWS SDK Go presigned PUT expected to fail with XAmzContentSHA256Mismatch but got MissingContentLength",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 13 tests successfully.
```

What could be the reason of such a behavior ?

**Comment by nitisht** [comment]
we’ll take a look @zaibon

**Comment by nitisht** [comment]
@zaibon can you paste the command line you're using to start Mint, (ofcourse, remove any sensitive info)

**Comment by zaibon** [comment]
@nitisht 
`docker run -e SERVER_ENDPOINT={url} -e ACCESS_KEY={key} -e SECRET_KEY={secret} -e ENABLE_HTTPS=1 minio/mint`

**Comment by nitisht** [comment]
can you try `docker run -e SERVER_ENDPOINT={url} -e ACCESS_KEY={key} -e SECRET_KEY={secret} -e ENABLE_HTTPS=1 minio/mint mc`

**Comment by zaibon** [comment]
mc test works ok
```
(1/1) Running mc tests ... done in 3 minutes and 58 seconds

All tests ran successfully
```

**Comment by nitisht** [comment]
In that case, this looks like something to do with `aws-sdk-go` tests that we have. Can you try all other SDKs in mint, 

`docker run -e SERVER_ENDPOINT={url} -e ACCESS_KEY={key} -e SECRET_KEY={secret} -e ENABLE_HTTPS=1 minio/mint mc awscli aws-sdk-php aws-sdk-ruby aws-sdk-java minio-go minio-java minio-js minio-py minio-dotnet s3cmd`

**Comment by nitisht** [comment]
@zaibon closing this due to no response, feel free to reopen when you have more info
