### ISSUE TITLE
aws-sdk-ruby presignedPost send file first instead of last

### ISSUE THREAD

**Issue by trinity-1686a** [minio/mint#335]
From [AWS Doc](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html#RESTObjectPOST-requests-form-fields) : "The file or text content must be the last field in the form."

Looking at a pcap dump, and at how presignedPost is implemented, it does not follow AWS documentation, it sends `file` first, and everything else after.
It should be a matter of initializing `parts` to an empty array, and .push()ing `file_part` after the loop [here](https://github.com/minio/mint/blob/master/run/core/aws-sdk-ruby/aws-stub-tests.rb#L793-L797)

**Comment by harshavardhana** [comment]
Feel  free to send a fix @trinity-1686a
