### ISSUE TITLE
Update Mint for release readiness

### ISSUE THREAD

**Issue by deekoder** [minio/mint#35]
- mc + minio sdks + aws java + aws cli  + aws php sdk run these in mint.
- Focus on correctness
- run this on minio server, minio gateway modes.

**Comment by NitishT** [comment]
Following tasks need to be taken up 

- Add test cases for `mc`
- Mint should not keep a local copy of tests for Minio SDKs. It is okay to keep local copies for tests for `mc`, `AWS-SDKs` and `AWS-CLI`.
- Update `minio-go` SDK tests to use smaller upload files. PR: (https://github.com/minio/minio-go/pull/727)
- Update and refactor `minio-java` SDK tests to use smaller upload files. 
- Update `minio-js` tests to run independently.
- Add `minio-dotnet` SDK tests to Mint.

**Comment by poornas** [comment]
@nitish,  I am sending a PR for the minio-java, minio-py ,minio-js and minio-go sdks to use smaller upload files created while building the image.

**Comment by NitishT** [comment]
Great @poornas

**Comment by harshavardhana** [comment]
> Mint should not keep a local copy of tests for Minio SDKs. It is okay to keep local copies for tests for mc, AWS-SDKs and AWS-CLI. Can be done once tests in Minio SDKs are updated as explained above.

For now the PR is send for awscli issue what other libraries are we looking here to test? should we add 

- aws-sdk-js
- aws-sdk-go
