### ISSUE TITLE
Add test cases for aws-java

### ISSUE THREAD

**Issue by nitisht** [minio/mint#37]
Add correctness test cases based on `aws-java` to Mint. Same test from minio-java, but use aws-java-sdk instead.

**Comment by NitishT** [comment]
This can use the tests created for minio-java (https://github.com/minio/mint/issues/42).

**Comment by deekoder** [comment]
can this be closed?

**Comment by NitishT** [comment]
I understand @balamurugana needs to add this still

**Comment by kannappanr** [comment]
@balamurugana @nitisht Are we planning to test aws-java SDK in mint? If not can this issue be closed?

**Comment by nitisht** [comment]
closing this for now, can be taken up later
