### ISSUE TITLE
[Feature] Maybe to add bucket as environment variable 

### ISSUE THREAD

**Issue by YuriyGavrilov** [minio/mint#389]
Maybe to add bucket as environment variable for making test inside one bucket 
We have new s3 and have access only on one specific bucket. don't know how to setup it. 
It is like root bucket but we can't ls it - need to specified it manually.

**Comment by harshavardhana** [comment]
That is impossible; all tests require creating buckets for tests as well. This is out of scope for this project.

**Comment by YuriyGavrilov** [comment]
thanks for info @harshavardhana - actually i can make mc mb s3/main_bucket/new_bucket 
but i can't create mc mb s3/new_bucket  <- here

**Comment by YuriyGavrilov** [comment]
> thanks for info @harshavardhana - actually i can make mc mb s3/main_bucket/new_bucket
> but i can't create mc mb s3/new_bucket <- here

thanks for info @harshavardhana - actually i can make mc mb s3/main_bucket/new_bucket
but i can't create mc mb s3/new_bucket <- here

**Comment by YuriyGavrilov** [comment]
also coulbe be good to have tls verification off to avoid - tls: failed to verify certificate: x509: certificate signed by unknown authority"
