### ISSUE TITLE
(Re)write test cases for minio-js

### ISSUE THREAD

**Issue by NitishT** [minio/mint#39]
Current minio-js has functional tests but we need to take a fresh look at the tests -

Tests should

- Be named to indicate the use case they are testing.
- Access all the public Minio server APIs via minio-js.
- Include one positive case and couple of boundary cases for each API.
- Have minimum file size uploads required to test multipart uploads.
- Refer test files from a static data directory as in (https://github.com/minio/minio-go/pull/727/files#diff-81a03de42b955e14be71afa81768a78cR52). This helps keep the Mint container light weight and avoids the file creation in runtime, making the tests run faster.

Tests should not include

- Big file uploads.
- Multiple tests related to the same API.

**Comment by NitishT** [comment]
@poornas , @krishnasrinivas has his changes here: https://github.com/krishnasrinivas/mint/tree/minio-js-fixes you can take a look

**Comment by poornas** [comment]
@nitisht, this was done in https://github.com/minio/minio-js/pull/601

**Comment by NitishT** [comment]
okay, closing this.
