### ISSUE TITLE
Add test cases for minio-py sdk

### ISSUE THREAD

**Issue by NitishT** [minio/mint#43]
Mint pulls functional test cases from `minio-py` sdk. 

Minio-Py SDK tests should be updated to address the following

- Named and commented to indicate the use case being tested.
- Access all the public Minio server APIs via minio-py.
- Include one positive case and couple of boundary cases for each API.

**Comment by vadmeste** [comment]
Taking this

**Comment by NitishT** [comment]
Filed an issue in minio-py as tests are pulled from there: https://github.com/minio/minio-py/issues/551

Closing this.
