### ISSUE TITLE
Add test cases for aws-cli

### ISSUE THREAD

**Issue by NitishT** [minio/mint#44]
Add correctness test cases based on `aws-cli` to Mint.

Tests should

- Access all the public Minio server APIs via aws-cli.
- Include one positive case and couple of boundary cases for each API.
- Have minimum file size uploads required to test multipart uploads.
- Refer test files from a static data directory as in (https://github.com/minio/minio-go/pull/727/files#diff-81a03de42b955e14be71afa81768a78cR52). This helps keep the Mint container light weight and avoids the file creation in runtime, making the tests run faster.

Tests should not include

- Big file uploads.
- Multiple tests related to the same API.

**Comment by harshavardhana** [comment]
Preliminary work is done.. now finishing the rest of the tests.

**Comment by NitishT** [comment]
are there any more tests you are planning to add @harshavardhana

**Comment by harshavardhana** [comment]
> are there any more tests you are planning to add @harshavardhana

There are two more will be sending them one related to 

- CopyObject API
- PresignedURL API
