### ISSUE TITLE
Add a note to use sudo for linux users.

### ISSUE THREAD

**Issue by deekoder** [minio/mint#45]

**Comment by harshavardhana** [comment]
why do you need sudo? `docker` can be configured to not run as root.

**Comment by deekoder** [comment]
that was the default behavior on ubuntu. I am sure it can be configured.

**Comment by harshavardhana** [comment]
> that was the default behavior on ubuntu. I am sure it can be configured. The error message is also misleading to think that docker is not running.

Yeah but that is something docker already documents. On how to run `docker`  - we mentioning `sudo` puts a wrong indication that we need root for some reason.  Our server docs for docker don't mention this as well  - including swarm etc.

**Comment by deekoder** [comment]
```
$ docker run -e SERVER_ENDPOINT=play.minio.io:9000 -e ACCESS_KEY=Q3AM3UQ867SPQQA43P2F -e SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG -e ENABLE_HTTPS=1 minio/mint 
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```
is what i got without sudo. New ubuntu installation. ps -ef  showed docker is running fine. Without configuration of docker to not run as root etc. Mint could put a note in the readme just to be thorough.

**Comment by harshavardhana** [comment]
> is what i got without sudo. New ubuntu installation. ps -ef showed docker is running fine. Without configuration of docker to not run as root etc. Mint could put a note in the readme just to be thorough.

My only problem with `sudo` is that it comes across as mint requires `sudo` not docker.  Docker documents this in their installation guide https://docs.docker.com/engine/installation/linux/linux-postinstall/ 

https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository
```
Docker is installed and running. You need to use sudo to run Docker commands. Continue to Linux postinstall to allow non-privileged users to run Docker commands and for other optional configuration steps.
```

For us it is simply `docker run` given that you have followed the docker installation guide properly.

**Comment by NitishT** [comment]
I think we can add a link for Docker installation. will send a PR for this.
