### ISSUE TITLE
Proposal: Accelerating building mint dev docker images

### ISSUE THREAD

**Issue by vadmeste** [minio/mint#59]
It is very slow to build a Mint docker image to check if everything is okay. We do a lot of iterations of writing code and testing, so this slowness is bad for us.

Why building the image is slow? The reason is that our docker script does a lot of tasks to download and install all dependencies. Since it is generally considered better to include the least possible number of RUN commands in a docker file, I suggest to make an exception for Dockerfile.dev.

In Dockerfile.dev, we can call RUN only twice:
*) The first RUN will init, download and install all dependencies.
*) The second RUN will copy our tests code.

Dockerfile and Dockerfile.dev should be similar, the only difference is that RUN in Dockerfile will be splitted into two RUNs in Dockerfile.dev

**Comment by harshavardhana** [comment]
Agree to split the layers to avoid updating ubuntu @vadmeste

**Comment by vadmeste** [comment]
Taking this

**Comment by NitishT** [comment]
Closed by #65
