### ISSUE TITLE
Add additional ruby tests in mint

### ISSUE THREAD

**Issue by deekoder** [minio/mint#62]
Add correctness test cases based on aws-ruby to Mint. Tests should be

- Named and commented to indicate the use case being tested.
- Access all the public Minio server APIs via aws-ruby.
- Include one positive case and couple of boundary cases for each API.
- Use streaming files as preferred way to generate files for testing. (This can be a ref: https://github.com/minio/minio-java/pull/586) 
- Use static files only in case where streaming can't be used.

**Comment by NitishT** [comment]
PR sent for addressing this issue: https://github.com/minio/mint/pull/87

**Comment by NitishT** [comment]
Fixed by #87
