### ISSUE TITLE
Move long running tests to mint full test mode

### ISSUE THREAD

**Issue by nitisht** [minio/mint#75]
Once minio/minio-java#585 is implemented, following tests should move to mint `full` mode.

- Large file uploads.
- Unknown sized input stream of multipart test.  
- ListObject test with 1050 file uploads.

New modes can be added here: https://github.com/minio/mint/blob/master/tests.sh#L159

**Comment by kannappanr** [comment]
@balamurugana I think this has already been implemented. If you agree can you please close this issue?

**Comment by balamurugana** [comment]
@kannappanr reporter @nitisht needs to check and do that

**Comment by nitisht** [comment]
Closing this as minio-java has support for full and core mode
